improve example 01

diff --git a/examples/01/tests/chk_lib b/examples/01/tests/chk_lib
--- a/examples/01/tests/chk_lib
+++ b/examples/01/tests/chk_lib
@@ -5,13 +5,9 @@ if [[ -z $1 || -z $2  ]]; then
   exit 1
 fi
 
-echo_n() {
-  printf '%s' "$@"
-}
-
+. "$(dirname "$0")/cfut.sh" || { echo "cfut.sh not found"; exit 1; }
 . tent.sh || { echo "tent.sh not found"; exit 1; }
 
-lib_found=false
 var_name="$1"
 libsx=""
 shift
@@ -29,11 +25,10 @@ for lib in "${!LIBx2}" "$@"; do
   libsx="$(echo "$libsx" | sed -e 's/;/ /g')"
   if "$CC" $libsx -o ".zscfzFiles/chklib_$$.x" ".zscfzFiles/chklib_$$.c" &>/dev/null; then
     echo yes
-    lib_found=true
+    zsconfuz-push result "$var_name=$libsx"
     break
   fi
   echo no
 done
 
 rm -f ".zscfzFiles/chklib_$$."*
-$lib_found && printf "\000$var_name=$libsx\n"
diff --git a/examples/01/tests/compiler_info b/examples/01/tests/compiler_info
--- a/examples/01/tests/compiler_info
+++ b/examples/01/tests/compiler_info
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+. "$(dirname "$0")/cfut.sh" || { echo "cfut.sh not found"; exit 1; }
 . tent.sh || { echo "tent.sh not found"; exit 1; }
 
 printf "checking for $1 compiler version ... "
@@ -8,7 +9,7 @@ for i in --version -v -V -qversion; do
   temp="$("${!2}" "$i" 2>/dev/null | head -n 1)"
   if [ -n "$temp" ]; then
     echo "$temp"
-    printf "\000compiler_${2}_vers=\"$temp\"\n"
+    zsconfuz-push result "compiler_${2}_vers=\"$temp\""
     is_dn=true
     break
   fi
@@ -23,13 +24,5 @@ int main() {}
 EOF
 
 "${!2}" -o ".zscfzFiles/compiler_ctst_$1.x" "$tmpf" &>/dev/null
-if [ $? -eq 0 ]; then
-  echo "yes"
-  printf "\000compiler_${2}_works=1\n"
-else
-  echo "no"
-  printf "\000compiler_${2}_works=0\n"
-fi
-
-rm -f ".zscfzFiles/compiler_ctst_$1."*
-exit 0
+print_result "compiler_${2}_works"
+rm -f ".zscfzFiles/compiler_ctst_$1."* || true
diff --git a/examples/01/tests/find_prog b/examples/01/tests/find_prog
--- a/examples/01/tests/find_prog
+++ b/examples/01/tests/find_prog
@@ -5,9 +5,7 @@ if [[ -z $1 || -z $2 ]]; then
   exit 1
 fi
 
-echo_n() {
-  printf '%s' "$@"
-}
+. "$(dirname "$0")/cfut.sh" || { echo "cfut.sh not found"; exit 1; }
 
 prog_found=false
 var_name="$1"
@@ -20,10 +18,10 @@ for prog in ${!var_name} "$@"; do
   if [ -f "$real_path" ]; then
     echo "$real_path"
     prog_found=true
+    zsconfuz-push result "$var_name=$prog"
     break
   fi
   echo no
 done
 
-printf "\000$found_vn=$prog_found\n"
-$prog_found && printf "\000$var_name=$prog\n"
+zsconfuz-push result "$found_vn=$prog_found"
diff --git a/examples/01/tests/readlink b/examples/01/tests/readlink
--- a/examples/01/tests/readlink
+++ b/examples/01/tests/readlink
@@ -1,10 +1,6 @@
 #!/bin/bash
 
+. "$(dirname "$0")/cfut.sh" || { echo "cfut.sh not found"; exit 1; }
 echo -n "checking whether readlink -f works ... "
-if readlink -f "$0" &>/dev/null; then
-  echo yes
-  printf "\000READLINK_F_WORKS=1\n"
-else
-  echo no
-  printf "\000READLINK_F_WORKS=0\n"
-fi
+readlink -f "$0" &>/dev/null
+print_result READLINK_F_WORKS
